# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Batch_Calculate_Statistics.py
# Created on: 2021-08-05 11:40:22.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# Calculate batch statistics for ASCII files
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
BPI_Broad_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\BPI_Broad.asc"
BPI_Fine_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\BPI_Fine.asc"
Curvature_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Curvature.asc"
Depth_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Depth.asc"
Habitat_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Habitat.asc"
Mangrove_Dist_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Mangrove_Dist.asc"
Mean_Sum_DO_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Mean_Sum_DO.asc"
Mean_Sum_Sal_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Mean_Sum_Sal.asc"
Mean_Sum_Temp_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Mean_Sum_Temp.asc"
Mean_Win_DO_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Mean_Win_DO.asc"
Mean_Win_Sal_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Mean_Win_Sal.asc"
Mean_Win_Temp_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Mean_Win_Temp.asc"
Plan_Curve_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Plan_Curve.asc"
Rugosity_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Rugosity.asc"
Slope_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Slope.asc"
StDev_Depth_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\StDev_Depth.asc"
Batch_Calculate_Statistics_Succeeded = "true"

# Process: Batch Calculate Statistics
arcpy.BatchCalculateStatistics_management("Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\BPI_Broad.asc;Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\BPI_Fine.asc;Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Curvature.asc;Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Depth.asc;Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Habitat.asc;Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Mangrove_Dist.asc;Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Mean_Sum_DO.asc;Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Mean_Sum_Sal.asc;Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Mean_Sum_Temp.asc;Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Mean_Win_DO.asc;Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Mean_Win_Sal.asc;Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Mean_Win_Temp.asc;Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Plan_Curve.asc;Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Rugosity.asc;Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Slope.asc;Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\StDev_Depth.asc", "1", "1", "", "OVERWRITE")

