# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Seafloor_Morphology.py
# Created on: 2021-08-05 11:29:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Z:/Courtney/Stuart_MSc_Ch1/Tools_Software/btm-3.0-final/toolbox/btm.pyt")


# Local variables:
Full_Mosaic_DEM_tif = "Z:\\Courtney\\Stuart_MSc_Ch1\\Source_Data\\Job606638_ncei_nintharcsec_dem\\Full_Mosaic_DEM.tif"
Full_Mosaic_DEM__2_ = Full_Mosaic_DEM_tif
Stuart_MSc_Scratch_gdb = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Scratch.gdb"
Stuart_MSc_Scratch_gdb__2_ = Stuart_MSc_Scratch_gdb
Full_Mosaic_DEM = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Scratch.gdb\\Full_Mosaic_DEM"
Area_Raster__2_ = ""
Depth__2_ = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\Depth"
Depth__3_ = Depth__2_
Depth_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\Spatial_Predictors\\Depth.asc"
Depth = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\Depth"
Curvature__2_ = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\Curvature"
Prof_Curve = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\Prof_Curve"
Plan_Curve = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\Plan_Curve"
Full_Rugosity__2_ = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Scratch.gdb\\Full_Rugosity"
Full_Rugosity = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Scratch.gdb\\Full_Rugosity"
Rugosity = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\Rugosity"
Full_Slope = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Scratch.gdb\\Full_Slope"
Slope = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\Slope"
BPI_Broad__2_ = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\BPI_Broad"
BPI_Fine__2_ = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\BPI_Fine"
Temporary = "Z:\\Courtney\\Stuart_MSc_Ch1\\Temporary"
Temporary__4_ = Temporary
BPI_Broad_UnStd__2_ = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Scratch.gdb\\BPI_Broad_UnStd"
BPI_Fine_UnStd__2_ = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Scratch.gdb\\BPI_Fine_UnStd"
BPI_Broad_UnStd = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Scratch.gdb\\BPI_Broad_UnStd"
BPI_Fine_UnStd = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Scratch.gdb\\BPI_Fine_UnStd"
BPI_Broad = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\BPI_Broad"
BPI_Fine = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\BPI_Fine"
Stuart_MSc_Ch1_gdb = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Scratch.gdb"
arcpy.env.workspace = "Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb"

# Process: Raster To Geodatabase (multiple)
arcpy.RasterToGeodatabase_conversion("Z:\\Courtney\\Stuart_MSc_Ch1\\Source_Data\\Job606638_ncei_nintharcsec_dem\\Full_Mosaic_DEM.tif", Stuart_MSc_Scratch_gdb, "")

# Process: Define Projection (2)
arcpy.DefineProjection_management(Full_Mosaic_DEM, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]],VERTCS['NAVD_1988',VDATUM['North_American_Vertical_Datum_1988'],PARAMETER['Vertical_Shift',0.0],PARAMETER['Direction',1.0],UNIT['Meter',1.0]]")

# Process: Surface Area to Planar Area (2)
tempEnvironment0 = arcpy.env.parallelProcessingFactor
arcpy.env.parallelProcessingFactor = "10"
arcpy.surfacetoplanar_btm(Full_Mosaic_DEM__2_, Full_Rugosity, "true", Area_Raster__2_)
arcpy.env.parallelProcessingFactor = tempEnvironment0

# Process: ASCII to Raster
arcpy.ASCIIToRaster_conversion(Depth_asc, Depth, "FLOAT")

# Process: Define Projection
arcpy.DefineProjection_management(Depth__2_, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]],VERTCS['NAVD_1988',VDATUM['North_American_Vertical_Datum_1988'],PARAMETER['Vertical_Shift',0.0],PARAMETER['Direction',1.0],UNIT['Meter',1.0]]")

# Process: Curvature
tempEnvironment0 = arcpy.env.cellSizeProjectionMethod
arcpy.env.cellSizeProjectionMethod = "CONVERT_UNITS"
tempEnvironment1 = arcpy.env.snapRaster
arcpy.env.snapRaster = Depth (3)
tempEnvironment2 = arcpy.env.extent
arcpy.env.extent = Depth (3)
tempEnvironment3 = arcpy.env.cellSize
arcpy.env.cellSize = "MAXOF"
tempEnvironment4 = arcpy.env.mask
arcpy.env.mask = Depth (3)
arcpy.gp.Curvature_sa(Depth__3_, Curvature__2_, "1", Prof_Curve, Plan_Curve)
arcpy.env.cellSizeProjectionMethod = tempEnvironment0
arcpy.env.snapRaster = tempEnvironment1
arcpy.env.extent = tempEnvironment2
arcpy.env.cellSize = tempEnvironment3
arcpy.env.mask = tempEnvironment4

# Process: Extract by Mask (2)
tempEnvironment0 = arcpy.env.cellSizeProjectionMethod
arcpy.env.cellSizeProjectionMethod = "CONVERT_UNITS"
tempEnvironment1 = arcpy.env.snapRaster
arcpy.env.snapRaster = Depth (3)
tempEnvironment2 = arcpy.env.extent
arcpy.env.extent = Depth (3)
tempEnvironment3 = arcpy.env.cellSize
arcpy.env.cellSize = "MAXOF"
tempEnvironment4 = arcpy.env.mask
arcpy.env.mask = Depth (3)
arcpy.gp.ExtractByMask_sa(Full_Rugosity__2_, Depth__3_, Rugosity)
arcpy.env.cellSizeProjectionMethod = tempEnvironment0
arcpy.env.snapRaster = tempEnvironment1
arcpy.env.extent = tempEnvironment2
arcpy.env.cellSize = tempEnvironment3
arcpy.env.mask = tempEnvironment4

# Process: Slope (3)
arcpy.gp.Slope_sa(Full_Mosaic_DEM__2_, Full_Slope, "DEGREE", "1", "PLANAR", "METER")

# Process: Extract by Mask
tempEnvironment0 = arcpy.env.cellSizeProjectionMethod
arcpy.env.cellSizeProjectionMethod = "CONVERT_UNITS"
tempEnvironment1 = arcpy.env.snapRaster
arcpy.env.snapRaster = Depth (3)
tempEnvironment2 = arcpy.env.extent
arcpy.env.extent = Depth (3)
tempEnvironment3 = arcpy.env.cellSize
arcpy.env.cellSize = "MAXOF"
tempEnvironment4 = arcpy.env.mask
arcpy.env.mask = Depth (3)
arcpy.gp.ExtractByMask_sa(Full_Slope, Depth__3_, Slope)
arcpy.env.cellSizeProjectionMethod = tempEnvironment0
arcpy.env.snapRaster = tempEnvironment1
arcpy.env.extent = tempEnvironment2
arcpy.env.cellSize = tempEnvironment3
arcpy.env.mask = tempEnvironment4

# Process: Build Broad Scale BPI
tempEnvironment0 = arcpy.env.outputCoordinateSystem
arcpy.env.outputCoordinateSystem = ""
tempEnvironment1 = arcpy.env.cellSizeProjectionMethod
arcpy.env.cellSizeProjectionMethod = "CONVERT_UNITS"
tempEnvironment2 = arcpy.env.snapRaster
arcpy.env.snapRaster = Depth (3)
tempEnvironment3 = arcpy.env.extent
arcpy.env.extent = Depth (3)
tempEnvironment4 = arcpy.env.cellSize
arcpy.env.cellSize = "MAXOF"
tempEnvironment5 = arcpy.env.geographicTransformations
arcpy.env.geographicTransformations = ""
tempEnvironment6 = arcpy.env.mask
arcpy.env.mask = Depth (3)
arcpy.broadscalebpi_btm(Depth__3_, "25", "250", "1250", BPI_Broad_UnStd)
arcpy.env.outputCoordinateSystem = tempEnvironment0
arcpy.env.cellSizeProjectionMethod = tempEnvironment1
arcpy.env.snapRaster = tempEnvironment2
arcpy.env.extent = tempEnvironment3
arcpy.env.cellSize = tempEnvironment4
arcpy.env.geographicTransformations = tempEnvironment5
arcpy.env.mask = tempEnvironment6

# Process: Build Fine Scale BPI
tempEnvironment0 = arcpy.env.outputCoordinateSystem
arcpy.env.outputCoordinateSystem = ""
tempEnvironment1 = arcpy.env.cellSizeProjectionMethod
arcpy.env.cellSizeProjectionMethod = "CONVERT_UNITS"
tempEnvironment2 = arcpy.env.snapRaster
arcpy.env.snapRaster = Depth (3)
tempEnvironment3 = arcpy.env.extent
arcpy.env.extent = Depth (3)
tempEnvironment4 = arcpy.env.cellSize
arcpy.env.cellSize = "MAXOF"
tempEnvironment5 = arcpy.env.geographicTransformations
arcpy.env.geographicTransformations = ""
tempEnvironment6 = arcpy.env.mask
arcpy.env.mask = Depth (3)
arcpy.finescalebpi_btm(Depth__3_, "1", "25", "125", BPI_Fine_UnStd)
arcpy.env.outputCoordinateSystem = tempEnvironment0
arcpy.env.cellSizeProjectionMethod = tempEnvironment1
arcpy.env.snapRaster = tempEnvironment2
arcpy.env.extent = tempEnvironment3
arcpy.env.cellSize = tempEnvironment4
arcpy.env.geographicTransformations = tempEnvironment5
arcpy.env.mask = tempEnvironment6

# Process: Standardize BPIs
arcpy.standardizebpi_btm(BPI_Broad_UnStd__2_, "0.125545504289903", "1.37211083177851", BPI_Broad, BPI_Fine_UnStd__2_, "1.59588330117677E-02", "0.162626706238851", BPI_Fine)

# Process: Raster To Other Format (multiple)
arcpy.RasterToOtherFormat_conversion("Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\Curvature;Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\Prof_Curve;Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\Plan_Curve;Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\Rugosity;Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\Slope;Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\BPI_Broad;Z:\\Courtney\\Stuart_MSc_Ch1\\Geodatabases\\Stuart_MSc_Ch1.gdb\\BPI_Fine", Temporary, "TIFF")

# Process: Calculate Metrics (Depth Statistics)
tempEnvironment0 = arcpy.env.cellSizeProjectionMethod
arcpy.env.cellSizeProjectionMethod = "CONVERT_UNITS"
tempEnvironment1 = arcpy.env.snapRaster
arcpy.env.snapRaster = Depth (3)
tempEnvironment2 = arcpy.env.extent
arcpy.env.extent = Depth (3)
tempEnvironment3 = arcpy.env.cellSize
arcpy.env.cellSize = "MAXOF"
tempEnvironment4 = arcpy.env.mask
arcpy.env.mask = Depth (3)
arcpy.depthstatistics_btm(Depth__3_, "3", Stuart_MSc_Ch1_gdb, "'Standard Deviation'")
arcpy.env.cellSizeProjectionMethod = tempEnvironment0
arcpy.env.snapRaster = tempEnvironment1
arcpy.env.extent = tempEnvironment2
arcpy.env.cellSize = tempEnvironment3
arcpy.env.mask = tempEnvironment4

